version: "3"
services:
  database:
    image: mongo
    restart: always
    volumes:
      - "./database/db:/data/db"
#      - "./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      database:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
  scanner:
    build: scanner
    restart: always
    volumes:
      - "./scanner:/code"
    depends_on:
      database:
        condition: service_started
  dcbot:
    build: dcbot
    restart: always
    volumes:
      - "./dcbot:/code"
    depends_on:
      database:
        condition: service_started

